[package]
name = "notifications"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[lib]
name = "notifications"
crate-type = ["lib"]

[build-dependencies]
bindgen = "0.71.1"

[profile]
dev.panic = "abort"
release.panic = "abort"


[dependencies]
flagset = { version = "0.4.6", default-features = false }
thiserror = { version = "2.0.11", default-features = false }
wut = { path = "../wut-rs" }
